# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lab/mill/kc705/prokc705_test/prokc705_test.srcs/sources_1/ip/fifo_66x512_async_dprogfull/fifo_66x512_async_dprogfull.xci
# IP: The module: 'fifo_66x512_async_dprogfull' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/fifo_66x512_async_dprogfull/fifo_66x512_async_dprogfull.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_66x512_async_dprogfull'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/fifo_66x512_async_dprogfull/fifo_66x512_async_dprogfull_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_66x512_async_dprogfull'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/fifo_66x512_async_dprogfull/fifo_66x512_async_dprogfull_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_66x512_async_dprogfull'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/lab/mill/kc705/prokc705_test/prokc705_test.srcs/sources_1/ip/fifo_66x512_async_dprogfull/fifo_66x512_async_dprogfull.xci
# IP: The module: 'fifo_66x512_async_dprogfull' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/fifo_66x512_async_dprogfull/fifo_66x512_async_dprogfull.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_66x512_async_dprogfull'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/fifo_66x512_async_dprogfull/fifo_66x512_async_dprogfull_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_66x512_async_dprogfull'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/fifo_66x512_async_dprogfull/fifo_66x512_async_dprogfull_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_66x512_async_dprogfull'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
