# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lab/mill/kc705/prokc705_test/prokc705_test.srcs/sources_1/ip/fwft_64x512_afull/fwft_64x512_afull.xci
# IP: The module: 'fwft_64x512_afull' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/fwft_64x512_afull/fwft_64x512_afull.xdc
# XDC: The top module name and the constraint reference have the same name: 'fwft_64x512_afull'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/fwft_64x512_afull/fwft_64x512_afull_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fwft_64x512_afull'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/lab/mill/kc705/prokc705_test/prokc705_test.srcs/sources_1/ip/fwft_64x512_afull/fwft_64x512_afull.xci
# IP: The module: 'fwft_64x512_afull' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/fwft_64x512_afull/fwft_64x512_afull.xdc
# XDC: The top module name and the constraint reference have the same name: 'fwft_64x512_afull'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/fwft_64x512_afull/fwft_64x512_afull_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fwft_64x512_afull'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
