# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lab/mill/kc705/prokc705_test/prokc705_test.srcs/sources_1/ip/PCIeGen1x8If64/PCIeGen1x8If64.xci
# IP: The module: 'PCIeGen1x8If64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/PCIeGen1x8If64/source/PCIeGen1x8If64-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIeGen1x8If64'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/PCIeGen1x8If64/synth/PCIeGen1x8If64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIeGen1x8If64'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/lab/mill/kc705/prokc705_test/prokc705_test.srcs/sources_1/ip/PCIeGen1x8If64/PCIeGen1x8If64.xci
# IP: The module: 'PCIeGen1x8If64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/PCIeGen1x8If64/source/PCIeGen1x8If64-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIeGen1x8If64'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/PCIeGen1x8If64/synth/PCIeGen1x8If64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIeGen1x8If64'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
