# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/lab/mill/kc705/prokc705_test/prokc705_test.runs/synth_1/top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param tcl.collectionResultDisplayLimit 0
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/lab/mill/kc705/prokc705_test/prokc705_test.cache/wt [current_project]
set_property parent.project_path /home/lab/mill/kc705/prokc705_test/prokc705_test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/lab/mill/kc705/prokc705_test/prokc705_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/functions.vh
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/widths.vh
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/riffa.vh
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/ultrascale.vh
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/trellis.vh
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/types.vh
  /home/lab/mill/kc705/src/boards/kc705/riffa-k7.vh
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/xilinx.vh
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/tlp.vh
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/schedules.vh
}
read_verilog -library xil_defaultlib {
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/async_fifo.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/async_fifo_fwft.v
  /home/lab/mill/kc705/src/boards/kc705/aurora-dual.v
  /home/lab/mill/kc705/src/serdes/aurora/aurora-port-axi.v
  /home/lab/mill/kc705/src/serdes/aurora/aurora-port.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/channel.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/channel_128.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/channel_32.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/channel_64.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/counter.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/cross_domain_signal.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/demux.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/engine_layer.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/ff.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/fifo.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/fifo_packer_128.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/fifo_packer_32.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/fifo_packer_64.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/interrupt.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/interrupt_controller.v
  /home/lab/mill/kc705/src/serdes/aurora/k7-aurora-boot.v
  /home/lab/mill/kc705/src/boards/kc705/kc705-clk.v
  /home/lab/mill/kc705/src/core/link-act.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/mux.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/offset_flag_to_one_hot.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/offset_to_mask.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/one_hot_mux.v
  /home/lab/mill/kc705/src/icap/xilinx/pe-icap.v
  /home/lab/mill/kc705/src/pe-base/pe-intadd.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/pipeline.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/ram_1clk_1w_1r.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/ram_2clk_1w_1r.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/recv_credit_flow_ctrl.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/register.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/registers.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/reorder_queue.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/reorder_queue_input.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/reorder_queue_output.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/reset_controller.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/reset_extender.v
  /home/lab/mill/kc705/src/pcie/riffa/riffa-port-k7.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/riffa.v
  /home/lab/mill/kc705/src/pcie/riffa/riffa_wrapper_kc705.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/rotate.v
  /home/lab/mill/kc705/src/core/router.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/rx_engine_classic.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/rx_engine_ultrascale.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/rx_port_128.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/rx_port_32.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/rx_port_64.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/rx_port_channel_gate.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/rx_port_reader.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/rx_port_requester_mux.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/rxc_engine_128.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/rxc_engine_classic.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/rxc_engine_ultrascale.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/rxr_engine_128.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/rxr_engine_classic.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/rxr_engine_ultrascale.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/scsdpram.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/sg_list_reader_128.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/sg_list_reader_32.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/sg_list_reader_64.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/sg_list_requester.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/shiftreg.v
  /home/lab/mill/kc705/src/serdes/aurora/sofeof-axi.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/sync_fifo.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/syncff.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/translation_xilinx.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/tx_alignment_pipeline.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/tx_data_fifo.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/tx_data_pipeline.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/tx_data_shift.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/tx_engine.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/tx_engine_classic.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/tx_engine_selector.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/tx_engine_ultrascale.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/tx_hdr_fifo.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/tx_multiplexer.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/tx_multiplexer_128.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/tx_multiplexer_32.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/tx_multiplexer_64.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/tx_port_128.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/tx_port_32.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/tx_port_64.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/tx_port_buffer_128.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/tx_port_buffer_32.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/tx_port_buffer_64.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/tx_port_channel_gate_128.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/tx_port_channel_gate_32.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/tx_port_channel_gate_64.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/tx_port_monitor_128.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/tx_port_monitor_32.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/tx_port_monitor_64.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/tx_port_writer.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/txc_engine_classic.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/txc_engine_ultrascale.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/txr_engine_classic.v
  /home/lab/mill/kc705/src/pcie/riffa/src-riffa/txr_engine_ultrascale.v
  /home/lab/mill/kc705/src/pcie/riffa/xillybus-compat.v
  /home/lab/mill/kc705/src/boards/kc705/top.v
}
read_ip -quiet /home/lab/mill/kc705/prokc705_test/prokc705_test.srcs/sources_1/ip/fifo_66x512_async_dprogfull/fifo_66x512_async_dprogfull.xci
set_property used_in_implementation false [get_files -all /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/fifo_66x512_async_dprogfull/fifo_66x512_async_dprogfull.xdc]
set_property used_in_implementation false [get_files -all /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/fifo_66x512_async_dprogfull/fifo_66x512_async_dprogfull_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/fifo_66x512_async_dprogfull/fifo_66x512_async_dprogfull_ooc.xdc]

read_ip -quiet /home/lab/mill/kc705/prokc705_test/prokc705_test.srcs/sources_1/ip/kc705_sfp_slave/kc705_sfp_slave.xci
set_property used_in_implementation false [get_files -all /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/kc705_sfp_slave/kc705_sfp_slave_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/kc705_sfp_slave/kc705_sfp_slave_waivers.xdc]
set_property used_in_implementation false [get_files -all /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/kc705_sfp_slave/kc705_sfp_slave.xdc]
set_property used_in_implementation false [get_files -all /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/kc705_sfp_slave/kc705_sfp_slave_clocks.xdc]

read_ip -quiet /home/lab/mill/kc705/prokc705_test/prokc705_test.srcs/sources_1/ip/fifo_64x512_32_async_afull/fifo_64x512_32_async_afull.xci
set_property used_in_implementation false [get_files -all /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/fifo_64x512_32_async_afull/fifo_64x512_32_async_afull.xdc]
set_property used_in_implementation false [get_files -all /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/fifo_64x512_32_async_afull/fifo_64x512_32_async_afull_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/fifo_64x512_32_async_afull/fifo_64x512_32_async_afull_ooc.xdc]

read_ip -quiet /home/lab/mill/kc705/prokc705_test/prokc705_test.srcs/sources_1/ip/PCIeGen1x8If64/PCIeGen1x8If64.xci
set_property used_in_implementation false [get_files -all /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/PCIeGen1x8If64/source/PCIeGen1x8If64-PCIE_X0Y0.xdc]
set_property used_in_implementation false [get_files -all /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/PCIeGen1x8If64/synth/PCIeGen1x8If64_ooc.xdc]

read_ip -quiet /home/lab/mill/kc705/prokc705_test/prokc705_test.srcs/sources_1/ip/clk_200_50_100/clk_200_50_100.xci
set_property used_in_implementation false [get_files -all /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/clk_200_50_100/clk_200_50_100_board.xdc]
set_property used_in_implementation false [get_files -all /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/clk_200_50_100/clk_200_50_100.xdc]
set_property used_in_implementation false [get_files -all /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/clk_200_50_100/clk_200_50_100_ooc.xdc]

read_ip -quiet /home/lab/mill/kc705/prokc705_test/prokc705_test.srcs/sources_1/ip/fwft_64x512_afull/fwft_64x512_afull.xci
set_property used_in_implementation false [get_files -all /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/fwft_64x512_afull/fwft_64x512_afull.xdc]
set_property used_in_implementation false [get_files -all /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/fwft_64x512_afull/fwft_64x512_afull_ooc.xdc]

read_ip -quiet /home/lab/mill/kc705/prokc705_test/prokc705_test.srcs/sources_1/ip/fifo_64x512_afull/fifo_64x512_afull.xci
set_property used_in_implementation false [get_files -all /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/fifo_64x512_afull/fifo_64x512_afull.xdc]
set_property used_in_implementation false [get_files -all /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/fifo_64x512_afull/fifo_64x512_afull_ooc.xdc]

read_ip -quiet /home/lab/mill/kc705/prokc705_test/prokc705_test.srcs/sources_1/ip/kc705_sma_6g_frame/kc705_sma_6g_frame.xci
set_property used_in_implementation false [get_files -all /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/kc705_sma_6g_frame/kc705_sma_6g_frame_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/kc705_sma_6g_frame/kc705_sma_6g_frame_waivers.xdc]
set_property used_in_implementation false [get_files -all /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/kc705_sma_6g_frame/kc705_sma_6g_frame.xdc]
set_property used_in_implementation false [get_files -all /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/kc705_sma_6g_frame/kc705_sma_6g_frame_clocks.xdc]

read_ip -quiet /home/lab/mill/kc705/prokc705_test/prokc705_test.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/ila_0/ila_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/lab/mill/kc705/src/boards/kc705/kc705.xdc
set_property used_in_implementation false [get_files /home/lab/mill/kc705/src/boards/kc705/kc705.xdc]

read_xdc /home/lab/mill/kc705/src/boards/kc705/riffa.xdc
set_property used_in_implementation false [get_files /home/lab/mill/kc705/src/boards/kc705/riffa.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/lab/mill/kc705/prokc705_test/prokc705_test.srcs/utils_1/imports/synth_1/top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top -part xc7k325tffg900-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
