# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lab/mill/kc705/prokc705_test/prokc705_test.srcs/sources_1/ip/kc705_sfp_slave/kc705_sfp_slave.xci
# IP: The module: 'kc705_sfp_slave' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/kc705_sfp_slave/kc705_sfp_slave_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kc705_sfp_slave'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/kc705_sfp_slave/kc705_sfp_slave_waivers.xdc
# XDC: The top module name and the constraint reference have the same name: 'kc705_sfp_slave'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/kc705_sfp_slave/kc705_sfp_slave.xdc
# XDC: The top module name and the constraint reference have the same name: 'kc705_sfp_slave'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/kc705_sfp_slave/kc705_sfp_slave_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'kc705_sfp_slave'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/lab/mill/kc705/prokc705_test/prokc705_test.srcs/sources_1/ip/kc705_sfp_slave/kc705_sfp_slave.xci
# IP: The module: 'kc705_sfp_slave' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/kc705_sfp_slave/kc705_sfp_slave_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kc705_sfp_slave'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/kc705_sfp_slave/kc705_sfp_slave_waivers.xdc
# XDC: The top module name and the constraint reference have the same name: 'kc705_sfp_slave'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/kc705_sfp_slave/kc705_sfp_slave.xdc
# XDC: The top module name and the constraint reference have the same name: 'kc705_sfp_slave'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/kc705_sfp_slave/kc705_sfp_slave_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'kc705_sfp_slave'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
