# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lab/mill/kc705/prokc705_test/prokc705_test.srcs/sources_1/ip/clk_200_50_100/clk_200_50_100.xci
# IP: The module: 'clk_200_50_100' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/clk_200_50_100/clk_200_50_100_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_200_50_100'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/clk_200_50_100/clk_200_50_100.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_200_50_100'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/clk_200_50_100/clk_200_50_100_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_200_50_100'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/lab/mill/kc705/prokc705_test/prokc705_test.srcs/sources_1/ip/clk_200_50_100/clk_200_50_100.xci
# IP: The module: 'clk_200_50_100' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/clk_200_50_100/clk_200_50_100_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_200_50_100'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/clk_200_50_100/clk_200_50_100.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_200_50_100'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/lab/mill/kc705/prokc705_test/prokc705_test.gen/sources_1/ip/clk_200_50_100/clk_200_50_100_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_200_50_100'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
